wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.7
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.05259574781300673
optimizer:
  value: rmsprop
weights_limit:
  value: 0.04551777938542114
