wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.7
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.0757229864182374
optimizer:
  value: adam
weights_limit:
  value: 0.033717792233273265
