wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.4
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.060142604538450814
optimizer:
  value: rmsprop
weights_limit:
  value: 0.07817672693537984
