wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.4
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.03983933771767904
optimizer:
  value: rmsprop
weights_limit:
  value: 0.0713748178927323
