wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.4
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.020464191705638353
optimizer:
  value: adam
weights_limit:
  value: 0.08229499811434252
