wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.4
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.042159498492940255
optimizer:
  value: sgd
weights_limit:
  value: 0.04844569332745736
