wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.5
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.025055318051794537
optimizer:
  value: rmsprop
weights_limit:
  value: 0.07200280379771787
