# Pipeline directory
PipelineDir: '/home/t.afanasyeva/MATseq'
# Shared
ProjectID: TA
SampleDir: '/home/t.afanasyeva/MATseq/experiment/raw_data'
WorkDir: '/home/t.afanasyeva/MATseq/temp'
Threads: 30
Paired: ['R1', 'R2']
# fastp
QualityScore: 15
LengthRequired: 36
