wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.1
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.02751961979238745
optimizer:
  value: rmsprop
weights_limit:
  value: 0.06663889899575849
