wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.04638965009588064
optimizer:
  value: sgd
weights_limit:
  value: 0.035164998723959236
