wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.2
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.09410102030876089
optimizer:
  value: adam
weights_limit:
  value: 0.04661461633947713
