wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.3
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.08617026580370012
optimizer:
  value: adam
weights_limit:
  value: 0.013002342025545918
