wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.2
epochs:
  value: 300
l1:
  value: 32
l2:
  value: 56
learning_rate:
  value: 0.042561995898813376
optimizer:
  value: adam
weights_limit:
  value: 0.0730952348155145
