wandb_version: 1

batch_size:
  desc: null
  value: 4
dropout_rates:
  desc: null
  value: 0.4
epochs:
  desc: null
  value: 280
l1:
  desc: null
  value: 56
l2:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.016569101798771597
weights_limit:
  desc: null
  value: 0.02710669250266189
activation:
  desc: null
  value: relu
loss:
  desc: null
  value: categorical_crossentropy
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693343150.301353
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
