wandb_version: 1

batch_size:
  desc: null
  value: 12
dropout_rates:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 120
l1:
  desc: null
  value: 128
l2:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.003593067277396394
weights_limit:
  desc: null
  value: 0.013115597830917931
activation:
  desc: null
  value: relu
loss:
  desc: null
  value: categorical_crossentropy
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693344300.693572
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
