wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.27656275225813
epochs:
  value: 150
learning_rate:
  value: 0.08504377528710148
optimizer:
  value: rmsprop
weights_limit:
  value: 0.08975537550980853
