wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.6881361606168601
epochs:
  value: 150
learning_rate:
  value: 0.05920366454681557
optimizer:
  value: sgd
weights_limit:
  value: 0.045889853232811306
