wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.7
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.07307373791196155
optimizer:
  value: adam
weights_limit:
  value: 0.028493312985765865
