wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.5
epochs:
  value: 120
l2:
  value: 8
learning_rate:
  value: 0.013387124725351038
optimizer:
  value: sgd
weights_limit:
  value: 0.027500108983265888
