# Raw data placed here
SampleDir: "~/research_storage/Processing/Lab - Van Dam/datasets/MATseq/105659"


# Working directory
WorkDir: "~/MAT_rnaseq/pipeline/results"


# Reference genome
GenomeDir: "~/reference_genome/GRCh38_GCA_000001405.15"


# Number of cores to use
Threads: 42

