wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.03391641191590131
optimizer:
  value: rmsprop
weights_limit:
  value: 0.012195727601269309
