wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.6
epochs:
  value: 300
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.012924623076729942
optimizer:
  value: rmsprop
weights_limit:
  value: 0.07956257757157624
