wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.6
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.0365042265702903
optimizer:
  value: rmsprop
weights_limit:
  value: 0.07895840212983973
