wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.5
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 6
learning_rate:
  value: 0.037176433580063464
weights_limit:
  value: 0.0701696248564341
