wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.1
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 56
learning_rate:
  value: 0.04865522629637402
optimizer:
  value: sgd
weights_limit:
  value: 0.08908364179854544
