wandb_version: 1

batch_size:
  desc: null
  value: 12
dropout_rates:
  desc: null
  value: 0.7
epochs:
  desc: null
  value: 200
l1:
  desc: null
  value: 32
l2:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.03442229817337811
optimizer:
  desc: null
  value: adam
weights_limit:
  desc: null
  value: 0.013745628318022066
activation:
  desc: null
  value: relu
loss:
  desc: null
  value: categorical_crossentropy
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693341802.254208
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
