wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693318712.144753
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 1
      - 5
