wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.2
epochs:
  value: 300
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.06897650477349869
optimizer:
  value: sgd
weights_limit:
  value: 0.01617219688550034
