wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.6
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.09186438746698256
optimizer:
  value: sgd
weights_limit:
  value: 0.03380011530854201
