wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.5
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.08901029708928584
optimizer:
  value: sgd
weights_limit:
  value: 0.06705784266391167
