wandb_version: 1

batch_size:
  desc: null
  value: 15
dropout_rates:
  desc: null
  value: 0.8
epochs:
  desc: null
  value: 300
l1:
  desc: null
  value: 16
l2:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.08093918741897775
optimizer:
  desc: null
  value: sgd
weights_limit:
  desc: null
  value: 0.015251635415647957
activation:
  desc: null
  value: relu
loss:
  desc: null
  value: categorical_crossentropy
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693335294.906303
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
