wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.6
epochs:
  value: 200
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.09074782466555098
optimizer:
  value: sgd
weights_limit:
  value: 0.021418124167552045
