wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.1
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.008885284911964456
optimizer:
  value: sgd
weights_limit:
  value: 0.057536082699962784
