wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.3
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.07316499009159676
optimizer:
  value: rmsprop
weights_limit:
  value: 0.041803297984029174
