wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.6
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.09508049772528612
optimizer:
  value: rmsprop
weights_limit:
  value: 0.04426363515676976
