wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.5
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 56
learning_rate:
  value: 0.007337794686470681
optimizer:
  value: rmsprop
weights_limit:
  value: 0.05869110724928825
