wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.3
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.05702598344238192
optimizer:
  value: sgd
weights_limit:
  value: 0.03242743430438669
