wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.7
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.03121875431907174
optimizer:
  value: sgd
weights_limit:
  value: 0.055929416472511005
