wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.9
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.083952618141144
optimizer:
  value: sgd
weights_limit:
  value: 0.0789315343597356
