wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.7
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.0499244352584186
optimizer:
  value: rmsprop
weights_limit:
  value: 0.08302758647001912
