wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.9
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.048576333734693895
optimizer:
  value: adam
weights_limit:
  value: 0.07910804885092514
