wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.4
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.042258074763943325
optimizer:
  value: adam
weights_limit:
  value: 0.04780018846524585
