wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.7
epochs:
  value: 300
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.011015855902738072
optimizer:
  value: sgd
weights_limit:
  value: 0.08849405537435592
