wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.5
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.06035642394739255
optimizer:
  value: sgd
weights_limit:
  value: 0.04719701703107795
