wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.3
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.07933047863146364
optimizer:
  value: rmsprop
weights_limit:
  value: 0.042687537564728296
