wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.2
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.061078959576663934
optimizer:
  value: rmsprop
weights_limit:
  value: 0.037692729453740144
