wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.5
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.0646255938590844
optimizer:
  value: sgd
weights_limit:
  value: 0.010779871689166928
