wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.5
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.09522144757462718
optimizer:
  value: rmsprop
weights_limit:
  value: 0.07925334346745865
