wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.3
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.025924960754998127
optimizer:
  value: adam
weights_limit:
  value: 0.06932863072522977
