wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.3
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.07754924651490443
optimizer:
  value: rmsprop
weights_limit:
  value: 0.0946355259716926
