wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.8
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.013224459459774265
optimizer:
  value: rmsprop
weights_limit:
  value: 0.022811044859302528
