wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.9
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.01177443503649582
optimizer:
  value: sgd
weights_limit:
  value: 0.031234891957601194
