wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.3
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.034535511871374935
optimizer:
  value: sgd
weights_limit:
  value: 0.025128623974601662
