wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.1
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.0003934913871573118
optimizer:
  value: sgd
weights_limit:
  value: 0.09226580898313012
