wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.01718800266940948
optimizer:
  value: adam
weights_limit:
  value: 0.09851038622366132
