wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.3
epochs:
  value: 200
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.011120392458095731
optimizer:
  value: rmsprop
weights_limit:
  value: 0.03199837034138948
