wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.3
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.08459313798613047
optimizer:
  value: adam
weights_limit:
  value: 0.04016254576298504
