wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.6
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.034766232591004184
optimizer:
  value: sgd
weights_limit:
  value: 0.06991885736595249
