wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.8
epochs:
  value: 300
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.03913892739367522
optimizer:
  value: rmsprop
weights_limit:
  value: 0.09323763575744896
