wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.6
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 56
learning_rate:
  value: 0.014439746100012625
optimizer:
  value: adam
weights_limit:
  value: 0.050855457018509534
