wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.8
epochs:
  value: 200
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.01029512644858966
optimizer:
  value: adam
weights_limit:
  value: 0.043795328732728726
