wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.7
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.05441066935318515
optimizer:
  value: rmsprop
weights_limit:
  value: 0.015415906262071
