wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.4
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.03150325080731568
optimizer:
  value: sgd
weights_limit:
  value: 0.05667831896769001
