wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.7
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.09591867996557855
optimizer:
  value: adam
weights_limit:
  value: 0.05145673039294088
