wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.7
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.011243462688163348
optimizer:
  value: rmsprop
weights_limit:
  value: 0.018745570220449967
