wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.3
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.06684100004512669
optimizer:
  value: rmsprop
weights_limit:
  value: 0.06679742021951839
