wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.9
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.010567449545960525
optimizer:
  value: adam
weights_limit:
  value: 0.0248724340568633
