wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.2
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.09326982650943784
optimizer:
  value: adam
weights_limit:
  value: 0.035847854733675896
