wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.3
epochs:
  value: 300
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.07184725571199072
optimizer:
  value: rmsprop
weights_limit:
  value: 0.07887750188123419
