wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.1
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.08380178560846037
optimizer:
  value: adam
weights_limit:
  value: 0.04991582147382451
