wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.5
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.07681510204238097
optimizer:
  value: adam
weights_limit:
  value: 0.020122773673440578
