wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.6
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.09347056489426142
optimizer:
  value: rmsprop
weights_limit:
  value: 0.03935786053095055
