wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.015373333674951972
optimizer:
  value: sgd
weights_limit:
  value: 0.028756446617006905
