wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.2
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.08158668665238303
optimizer:
  value: sgd
weights_limit:
  value: 0.03924600733066474
