wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.8
epochs:
  value: 200
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.022316718063875324
optimizer:
  value: rmsprop
weights_limit:
  value: 0.024470253285259452
