wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.8
epochs:
  value: 300
l1:
  value: 32
l2:
  value: 56
learning_rate:
  value: 0.09408563471379712
optimizer:
  value: rmsprop
weights_limit:
  value: 0.04332477238374716
