wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.3
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.02061399046151296
optimizer:
  value: adam
weights_limit:
  value: 0.07551658320007762
