wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.9
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.04471403107281295
optimizer:
  value: rmsprop
weights_limit:
  value: 0.04061491345428281
