wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.7
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 56
learning_rate:
  value: 0.025301811244954165
optimizer:
  value: rmsprop
weights_limit:
  value: 0.06337577252942286
