wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.1
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.05477916265794343
optimizer:
  value: rmsprop
weights_limit:
  value: 0.02316510671380447
