wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.8
epochs:
  value: 200
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.0979733886657527
optimizer:
  value: rmsprop
weights_limit:
  value: 0.03953015325267741
