wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.2
epochs:
  value: 200
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.08355956525672782
optimizer:
  value: sgd
weights_limit:
  value: 0.07970002807289596
