wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.4
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.02989521756117426
optimizer:
  value: adam
weights_limit:
  value: 0.0584007472920407
