wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.2
epochs:
  value: 300
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.02137319982603828
optimizer:
  value: adam
weights_limit:
  value: 0.06355642495567664
