wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.5
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.08237047820329556
optimizer:
  value: adam
weights_limit:
  value: 0.014334546961137978
