wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.8
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.09074201566892866
optimizer:
  value: adam
weights_limit:
  value: 0.04247678496336466
