wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.6
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.04957945103742705
optimizer:
  value: adam
weights_limit:
  value: 0.08213939718021729
