wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.3
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.025999759441523423
optimizer:
  value: rmsprop
weights_limit:
  value: 0.02024349720140213
