wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.9
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.07941237067385087
optimizer:
  value: rmsprop
weights_limit:
  value: 0.015973864810599883
