wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.6
epochs:
  value: 300
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.018613217810917383
optimizer:
  value: rmsprop
weights_limit:
  value: 0.026973798010553184
