wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.7
epochs:
  value: 300
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.05492893613612546
optimizer:
  value: sgd
weights_limit:
  value: 0.04207390860491039
