wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.5
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 56
learning_rate:
  value: 0.05550063896347392
optimizer:
  value: sgd
weights_limit:
  value: 0.012462614302918826
