wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.5
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.02209172803897743
optimizer:
  value: rmsprop
weights_limit:
  value: 0.021997178773839218
