wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.3
epochs:
  value: 150
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.08693897650526515
optimizer:
  value: sgd
weights_limit:
  value: 0.06539558875337508
