wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.7
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.05669340909214255
optimizer:
  value: adam
weights_limit:
  value: 0.0818160395343135
