wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.8
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.053822325045650744
optimizer:
  value: sgd
weights_limit:
  value: 0.03454758734010459
