wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.6
epochs:
  value: 200
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.08700457214841825
optimizer:
  value: sgd
weights_limit:
  value: 0.09221141579846376
