wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.8
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.01447111080453891
optimizer:
  value: adam
weights_limit:
  value: 0.08599783885951594
