wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.8
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.0009840392610307137
optimizer:
  value: adam
weights_limit:
  value: 0.06478859626570063
