wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.8
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.004821313066233725
optimizer:
  value: sgd
weights_limit:
  value: 0.014960738518037444
