wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.5
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.03588174957499751
optimizer:
  value: rmsprop
weights_limit:
  value: 0.05136067463792018
