wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.1
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.06678388049635825
optimizer:
  value: adam
weights_limit:
  value: 0.07630753226623856
