wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.3
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.07458223731829568
optimizer:
  value: adam
weights_limit:
  value: 0.06563139898781037
