wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.7
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.055175086331677066
optimizer:
  value: adam
weights_limit:
  value: 0.07253094608776803
