wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 280
l1:
  value: 84
l2:
  value: 15
learning_rate:
  value: 0.04381237831190163
weights_limit:
  value: 0.05637744096696444
