wandb_version: 1

hidden_units:
  desc: null
  value:
  - 8
dropout_rates:
  desc: null
  value:
  - 0.2
num_layers:
  desc: null
  value:
  - 2
batch_size:
  desc: null
  value:
  - 5
optimizer:
  desc: null
  value:
  - adam
activation:
  desc: null
  value:
  - relu
weights_limit:
  desc: null
  value:
  - 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693308631.48091
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 1
      - 5
