wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.7
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.08396331950339318
optimizer:
  value: sgd
weights_limit:
  value: 0.08369213879322827
