wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.8
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.08768733838527228
optimizer:
  value: rmsprop
weights_limit:
  value: 0.03248396527951075
