wandb_version: 1

batch_size:
  desc: null
  value: 12
dropout_rates:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 120
l1:
  desc: null
  value: 128
l2:
  desc: null
  value: 15
learning_rate:
  desc: null
  value: 0.027695460615262252
weights_limit:
  desc: null
  value: 0.025807554099204794
activation:
  desc: null
  value: relu
loss:
  desc: null
  value: categorical_crossentropy
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693343968.83492
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
