wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.09542349117580216
optimizer:
  value: rmsprop
weights_limit:
  value: 0.05578784584363846
