wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.8
epochs:
  value: 300
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.030143413310306386
optimizer:
  value: sgd
weights_limit:
  value: 0.07630295005962302
