wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.6
epochs:
  value: 300
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.021167929391109314
optimizer:
  value: rmsprop
weights_limit:
  value: 0.07659426561937041
