wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.5
epochs:
  value: 300
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.04858328964591086
optimizer:
  value: sgd
weights_limit:
  value: 0.09259408125525226
