wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.2
epochs:
  value: 120
l1:
  value: 84
l2:
  value: 32
learning_rate:
  value: 0.0015625477702378948
weights_limit:
  value: 0.010277393331172745
