wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.2
epochs:
  value: 200
l1:
  value: 32
l2:
  value: 15
learning_rate:
  value: 0.0007153254951470822
weights_limit:
  value: 0.01098102766490688
