wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 128
l2:
  value: 15
learning_rate:
  value: 0.027695460615262252
weights_limit:
  value: 0.025807554099204794
