wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.013741997458070329
weights_limit:
  value: 0.04893727015241557
