wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 6
learning_rate:
  value: 0.02296617523441232
weights_limit:
  value: 0.024062099757804805
