wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 6
learning_rate:
  value: 0.026171867489019004
weights_limit:
  value: 0.019039936001856456
