wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.5
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 6
learning_rate:
  value: 0.016653570526628754
weights_limit:
  value: 0.05107219629234161
