wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 200
l1:
  value: 84
l2:
  value: 32
learning_rate:
  value: 0.013930435968491065
weights_limit:
  value: 0.037113747443594206
