wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 15
learning_rate:
  value: 0.022569347732810153
weights_limit:
  value: 0.021560278152231008
