wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 6
learning_rate:
  value: 0.019277854384817997
weights_limit:
  value: 0.018848237157551257
