wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.3
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 8
learning_rate:
  value: 0.019085885982843383
weights_limit:
  value: 0.02581222738150975
