wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.005193804303657173
weights_limit:
  value: 0.011465278691769998
