wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.3
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 15
learning_rate:
  value: 0.01262362617706944
weights_limit:
  value: 0.0192009799141008
