wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 15
learning_rate:
  value: 0.009668642744336408
weights_limit:
  value: 0.013388473246468378
