wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.3
epochs:
  value: 120
l1:
  value: 128
l2:
  value: 8
learning_rate:
  value: 0.00893507500413684
weights_limit:
  value: 0.011474385264110338
