wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.3
epochs:
  value: 200
l1:
  value: 84
l2:
  value: 8
learning_rate:
  value: 0.015555604492678544
weights_limit:
  value: 0.0396192593734517
