wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.3
epochs:
  value: 200
l1:
  value: 84
l2:
  value: 32
learning_rate:
  value: 0.010748525222851487
weights_limit:
  value: 0.01684873703731232
