wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.1
epochs:
  value: 200
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.012158177248575618
weights_limit:
  value: 0.011639203188433768
