wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.2
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 15
learning_rate:
  value: 0.02020396195648131
weights_limit:
  value: 0.016047938064348035
