wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.3
epochs:
  value: 200
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.005436080402110116
weights_limit:
  value: 0.01474033840531418
