wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 128
l2:
  value: 15
learning_rate:
  value: 0.026748758032287996
weights_limit:
  value: 0.02715800091743549
