wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.2
epochs:
  value: 200
l1:
  value: 84
l2:
  value: 15
learning_rate:
  value: 0.007969011820842016
weights_limit:
  value: 0.029166531492405647
