wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.01286174832123833
weights_limit:
  value: 0.053500947868638446
