wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 280
l1:
  value: 128
l2:
  value: 8
learning_rate:
  value: 0.010925909323437047
weights_limit:
  value: 0.07410848261027216
