wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 8
learning_rate:
  value: 0.005294410775514462
weights_limit:
  value: 0.070569322366778
