wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.4
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.00299661650069266
weights_limit:
  value: 0.014480850368535522
