wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.003594683850838623
weights_limit:
  value: 0.017170764597647187
