wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.3
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 15
learning_rate:
  value: 0.003846540848691938
weights_limit:
  value: 0.01880222901509307
