wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.2
epochs:
  value: 120
l1:
  value: 84
l2:
  value: 32
learning_rate:
  value: 0.01118744765588177
weights_limit:
  value: 0.037233399763650026
