wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.4
epochs:
  value: 280
l1:
  value: 56
l2:
  value: 8
learning_rate:
  value: 0.016569101798771597
weights_limit:
  value: 0.02710669250266189
