wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.3
epochs:
  value: 280
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.00533594742825679
weights_limit:
  value: 0.011278256936810551
