wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.5
epochs:
  value: 200
l1:
  value: 128
l2:
  value: 32
learning_rate:
  value: 0.02793903241366815
weights_limit:
  value: 0.01560949522559184
