wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.4
epochs:
  value: 120
l1:
  value: 56
l2:
  value: 15
learning_rate:
  value: 0.006462967393088682
weights_limit:
  value: 0.011124869936646244
