wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 6
learning_rate:
  value: 0.0189087314211592
weights_limit:
  value: 0.03911803938838295
