wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.2
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.003230144657631677
weights_limit:
  value: 0.03684402178008961
