wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.4
epochs:
  value: 120
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.0004036886420726615
weights_limit:
  value: 0.02631375666274613
