wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.2
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 15
learning_rate:
  value: 0.005642730621473635
weights_limit:
  value: 0.04742783554713459
