wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.3
epochs:
  value: 120
l1:
  value: 128
l2:
  value: 32
learning_rate:
  value: 0.003593067277396394
weights_limit:
  value: 0.013115597830917931
