wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.005616116174454033
weights_limit:
  value: 0.02115235623927421
