wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 200
l1:
  value: 128
l2:
  value: 32
learning_rate:
  value: 0.005160870700043562
weights_limit:
  value: 0.010822179203975489
