wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 8
learning_rate:
  value: 0.01057508561846544
weights_limit:
  value: 0.034272622034893695
