wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.012140756089590707
weights_limit:
  value: 0.016491103063841724
