wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.3
epochs:
  value: 120
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.014074680415085762
weights_limit:
  value: 0.016708629980959216
