wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.4
epochs:
  value: 120
l1:
  value: 84
l2:
  value: 32
learning_rate:
  value: 0.004096665104985345
weights_limit:
  value: 0.017908617556237287
