wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 120
l1:
  value: 56
l2:
  value: 15
learning_rate:
  value: 0.0054636416912294756
weights_limit:
  value: 0.015448388060189932
