wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.3
epochs:
  value: 120
l1:
  value: 128
l2:
  value: 32
learning_rate:
  value: 0.010895374202124594
weights_limit:
  value: 0.02727113717764565
