wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 84
l2:
  value: 8
learning_rate:
  value: 0.04766358694955034
weights_limit:
  value: 0.053551692554685275
