wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 200
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.00097870127766403
weights_limit:
  value: 0.023184595750047488
