wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.5
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 15
learning_rate:
  value: 0.04879863044362516
weights_limit:
  value: 0.01292280833813227
