wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 280
l1:
  value: 56
l2:
  value: 8
learning_rate:
  value: 0.017279567807657485
weights_limit:
  value: 0.021043737095996537
