wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.2
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 8
learning_rate:
  value: 0.0001769423265969326
weights_limit:
  value: 0.012327291896862424
