wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 200
l1:
  value: 32
l2:
  value: 6
learning_rate:
  value: 0.02762621876431535
weights_limit:
  value: 0.02434030644424453
