wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.3
epochs:
  value: 200
l1:
  value: 32
l2:
  value: 8
learning_rate:
  value: 0.007526684896253355
weights_limit:
  value: 0.02168038136421672
