wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.4
epochs:
  value: 120
l1:
  value: 128
l2:
  value: 32
learning_rate:
  value: 0.026397015212264223
weights_limit:
  value: 0.03634758528852622
