wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.005433838386233988
weights_limit:
  value: 0.025569911965115225
