wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.3
epochs:
  value: 120
l1:
  value: 84
l2:
  value: 15
learning_rate:
  value: 0.00562203416440661
weights_limit:
  value: 0.02149064811977431
