wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.2
epochs:
  value: 280
l1:
  value: 56
l2:
  value: 6
learning_rate:
  value: 0.014684795371303565
weights_limit:
  value: 0.036530107777272426
