wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 128
l2:
  value: 6
learning_rate:
  value: 0.03780387801305105
weights_limit:
  value: 0.011383396921549905
