wandb_version: 1

batch_size:
  value: 8
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.011079549532086732
weights_limit:
  value: 0.04164662814444949
