wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.1
epochs:
  value: 120
l1:
  value: 32
l2:
  value: 15
learning_rate:
  value: 0.004252565762039628
weights_limit:
  value: 0.036245841661513976
