wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.4
epochs:
  value: 200
l1:
  value: 84
l2:
  value: 6
learning_rate:
  value: 0.03617534304138352
weights_limit:
  value: 0.02994546337772202
