wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 280
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.011977856405087726
weights_limit:
  value: 0.03000268333257636
