wandb_version: 1

batch_size:
  desc: null
  value: 12
dropout_rates:
  desc: null
  value: 0.7
epochs:
  desc: null
  value: 50
l1:
  desc: null
  value: 56
l2:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0568976146192226
optimizer:
  desc: null
  value: rmsprop
weights_limit:
  desc: null
  value: 0.0781517342904586
activation:
  desc: null
  value: relu
loss:
  desc: null
  value: categorical_crossentropy
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693335729.323184
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
