wandb_version: 1

batch_size:
  desc: null
  value: 567887
epochs:
  desc: null
  value: 150
learning_rate:
  desc: null
  value: 0.01731995849926852
optimizer:
  desc: null
  value: adam
hidden_units:
  desc: null
  value: 56
dropout_rates:
  desc: null
  value: 0.2
activation:
  desc: null
  value: relu
weights_limit:
  desc: null
  value: 0.01
loss:
  desc: null
  value: categorical_crossentropy
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693334098.878905
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
