wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.2
epochs:
  value: 300
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.098994865082908
optimizer:
  value: rmsprop
weights_limit:
  value: 0.08755870034637873
