wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.4
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.07101052301825939
optimizer:
  value: sgd
weights_limit:
  value: 0.010988895018299971
