wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.6
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.003567933773498557
optimizer:
  value: rmsprop
weights_limit:
  value: 0.021562786966032706
