wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.7
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 16
learning_rate:
  value: 0.09007229624275637
optimizer:
  value: sgd
weights_limit:
  value: 0.0373021354107231
