wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.6
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.011001196952886623
optimizer:
  value: sgd
weights_limit:
  value: 0.04484508629616653
