wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.1
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 56
learning_rate:
  value: 0.02351446917189378
optimizer:
  value: sgd
weights_limit:
  value: 0.08115947898547077
