wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.7
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.07995177600058308
optimizer:
  value: adam
weights_limit:
  value: 0.097717079230912
