wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.1
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.03420074342205363
optimizer:
  value: rmsprop
weights_limit:
  value: 0.04941275894795624
