wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.4
epochs:
  value: 300
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.050988914941952915
optimizer:
  value: rmsprop
weights_limit:
  value: 0.09942162315646776
