wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.1
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.0019892617574532832
optimizer:
  value: adam
weights_limit:
  value: 0.017413106734437862
