wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.2
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 56
learning_rate:
  value: 0.05829224106250109
optimizer:
  value: sgd
weights_limit:
  value: 0.06387643400558367
