wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.1
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.04093794405451036
optimizer:
  value: adam
weights_limit:
  value: 0.059152603789544206
