wandb_version: 1

batch_size:
  desc: null
  value: 6
dropout_rates:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 200
l1:
  desc: null
  value: 32
l2:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.00097870127766403
weights_limit:
  desc: null
  value: 0.023184595750047488
activation:
  desc: null
  value: relu
loss:
  desc: null
  value: categorical_crossentropy
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693344153.125979
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
