wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.6
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.08711443497215651
optimizer:
  value: sgd
weights_limit:
  value: 0.09779514010970045
