wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.5
epochs:
  value: 50
l1:
  value: 32
l2:
  value: 16
learning_rate:
  value: 0.07007974312498477
optimizer:
  value: adam
weights_limit:
  value: 0.0742102411873557
