wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.4
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 32
learning_rate:
  value: 0.05786528538274462
optimizer:
  value: rmsprop
weights_limit:
  value: 0.03405575577804114
