wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.5
epochs:
  value: 150
l1:
  value: 56
l2:
  value: 32
learning_rate:
  value: 0.07048619597617109
optimizer:
  value: adam
weights_limit:
  value: 0.050913138129715374
