wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.5
epochs:
  value: 300
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.06600971639572738
optimizer:
  value: sgd
weights_limit:
  value: 0.03250573481651877
