wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.4
epochs:
  value: 200
l1:
  value: 32
l2:
  value: 32
learning_rate:
  value: 0.02928633591261225
optimizer:
  value: adam
weights_limit:
  value: 0.030385151309695227
