wandb_version: 1

batch_size:
  value: 12
dropout_rates:
  value: 0.5
epochs:
  value: 280
l1:
  value: 84
l2:
  value: 15
learning_rate:
  value: 0.008110738047042182
optimizer:
  value: adam
weights_limit:
  value: 0.01353851829270458
