wandb_version: 1

batch_size:
  value: 6
dropout_rates:
  value: 0.9
epochs:
  value: 50
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.023380207606431155
optimizer:
  value: rmsprop
weights_limit:
  value: 0.039727086845611166
