wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.9
epochs:
  value: 50
l1:
  value: 56
l2:
  value: 16
learning_rate:
  value: 0.07894959703942664
optimizer:
  value: sgd
weights_limit:
  value: 0.08432536107136245
