wandb_version: 1

batch_size:
  value: 15
dropout_rates:
  value: 0.2
epochs:
  value: 150
l1:
  value: 16
l2:
  value: 56
learning_rate:
  value: 0.05775039631864699
optimizer:
  value: rmsprop
weights_limit:
  value: 0.08050801635924233
