wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.5
epochs:
  value: 134.74520163762892
l2:
  value: 6.501444725891889
learning_rate:
  value: 0.019973632144863022
optimizer:
  value: adam
weights_limit:
  value: 0.0785926554173722
