wandb_version: 1

batch_size:
  value: 4
dropout_rates:
  value: 0.5
epochs:
  value: 269.33471814591553
l2:
  value: 20.374396709189917
learning_rate:
  value: 0.041160125940807514
optimizer:
  value: sgd
weights_limit:
  value: 0.029990806754002865
