wandb_version: 1

batch_size:
  desc: null
  value: 4
dropout_rates:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 269.33471814591553
l2:
  desc: null
  value: 20.374396709189917
learning_rate:
  desc: null
  value: 0.041160125940807514
optimizer:
  desc: null
  value: sgd
weights_limit:
  desc: null
  value: 0.029990806754002865
l1:
  desc: null
  value: 56
activation:
  desc: null
  value: relu
loss:
  desc: null
  value: categorical_crossentropy
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693342250.764762
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
